// ai.js — AgroDoc AI v3.0
// FIX #8 — Cache versioning added (CACHE_VERSION exported)
const axios=require("axios");

// FIX #8 — Version string — update this when you add new diseases to the cache
// The frontend compares this against its stored version and refreshes if different
const CACHE_VERSION="2026.04.v3";

const LANG_PROMPTS={
  en:"Respond in clear simple English.",
  pcm:"Respond in Nigerian Pidgin English. Use 'Oga','e dey','make you','quick quick' naturally like a friendly Nigerian neighbour.",
  ha:"Respond in Hausa as spoken in northern Nigeria.",
  yo:"Respond in Yoruba as spoken in southwestern Nigeria.",
  ig:"Respond in Igbo as spoken in southeastern Nigeria.",
};
const CAT_INSTRUCTIONS={
  crops:"Diagnose a CROP or PLANT — disease, pest damage, or nutrient deficiency.",
  poultry:"Diagnose POULTRY (chicken, turkey, duck, guinea fowl) — disease or health problem.",
  fish:"Diagnose FISH or AQUACULTURE (catfish, tilapia, carp) — disease or water quality issue.",
  livestock:"Diagnose LIVESTOCK (cattle, goat, sheep, pig) — disease or health condition.",
};

// 30 cached diseases — covers all 4 farm sectors and all Nigerian regions
const OFFLINE_CACHE={
  // CROPS
  "cassava mosaic":{category:"crops",disease:"Cassava Mosaic Disease",subject:"Cassava",severity:"severe",description:"Yellow/green mosaic on leaves. Whitefly virus. 20–95% yield loss.",treatment:["Remove all infected plants immediately","Spray Confidor for whiteflies","Replant TME 419 or NR 8082","Keep field weed-free"],pesticide:"Confidor (Imidacloprid)",prevention:"Certified disease-free stems. Early planting.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Contact your state ADP for field support."},
  "cassava bacterial":{category:"crops",disease:"Cassava Bacterial Blight",subject:"Cassava",severity:"moderate",description:"Water-soaked leaf spots, stem cankers, wilting. Spreads via tools and rain.",treatment:["Remove and burn infected stems","Don't work in field when wet","Treat tools with bleach","Use healthy certified cuttings"],pesticide:"Copper-based bactericide spray",prevention:"Certified cuttings. Rotate fields. Disinfect tools.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "maize streak":{category:"crops",disease:"Maize Streak Virus",subject:"Maize",severity:"severe",description:"Yellow streaks on leaves. Leafhopper-spread. Up to 100% yield loss.",treatment:["Remove severely infected plants","Spray Karate for leafhoppers","Replant SAMMAZ 15 or SAMMAZ 27","Plant early in the season"],pesticide:"Karate (Lambda-cyhalothrin)",prevention:"Early planting. Resistant varieties. Weed control.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Contact your state ADP."},
  "maize stalk rot":{category:"crops",disease:"Maize Stalk Rot (Fusarium)",subject:"Maize",severity:"moderate",description:"Stalk softens and rots from base. Plant falls. Fungal disease in wet conditions.",treatment:["Harvest early before collapse","Improve field drainage","Widen spacing","Apply potassium fertilizer"],pesticide:"Prevention is best — no effective cure chemical",prevention:"Balanced NPK with potassium. Good drainage. Crop rotation.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "tomato blight":{category:"crops",disease:"Early Blight (Alternaria)",subject:"Tomato",severity:"moderate",description:"Brown target-pattern spots on lower leaves, spreading upward in wet weather.",treatment:["Remove infected leaves","Spray Ridomil Gold MZ every 7 days","Stake plants for airflow","Avoid overhead watering"],pesticide:"Ridomil Gold MZ or Funguran OH",prevention:"Crop rotation. Mulch base. Drip irrigation.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "tomato late blight":{category:"crops",disease:"Late Blight (Phytophthora)",subject:"Tomato",severity:"severe",description:"Dark water-soaked patches on leaves and fruit. White mould underneath. Fast-spreading.",treatment:["Spray Ridomil Gold immediately","Remove infected plants — very contagious","Avoid wet plants","Ensure good drainage"],pesticide:"Ridomil Gold MZ 68 WP — spray every 5 days in rainy season",prevention:"Resistant varieties. Avoid peak rainy season planting.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Contact your state ADP for emergency support."},
  "rice blast":{category:"crops",disease:"Rice Blast (Magnaporthe)",subject:"Rice",severity:"severe",description:"Diamond grey lesions with brown borders. Can destroy entire panicle and cause 100% loss.",treatment:["Apply Beam at first sign","Drain field 2-3 days","Reduce nitrogen fertilizer","Spray again if needed"],pesticide:"Beam (Tricyclazole) or Tilt (Propiconazole)",prevention:"Resistant varieties. Balanced NPK. Good drainage.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Contact your state ADP rice team."},
  "pepper wilt":{category:"crops",disease:"Pepper Wilt / Phytophthora",subject:"Pepper",severity:"moderate",description:"Sudden wilting with dark rot at stem base. Soil-borne disease in waterlogged conditions.",treatment:["Improve drainage immediately","Drench soil with Ridomil","Remove and burn affected plants","Don't replant pepper in same spot"],pesticide:"Ridomil Gold MZ (Metalaxyl + Mancozeb) soil drench",prevention:"Raised beds. Avoid waterlogging. 3-year rotation.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "yam anthracnose":{category:"crops",disease:"Yam Anthracnose",subject:"Yam",severity:"moderate",description:"Dark spots on leaves and stems. Leaves curl and die. Reduces tuber quality.",treatment:["Remove and destroy infected parts","Spray Dithane M-45 every 2 weeks","Widen plant spacing","Stake vines for air circulation"],pesticide:"Dithane M-45 (Mancozeb) or Copper Oxychloride",prevention:"Healthy setts. Wider spacing. Stake plants.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "groundnut rosette":{category:"crops",disease:"Groundnut Rosette Virus",subject:"Groundnut",severity:"severe",description:"Stunted plants, small yellow mottled leaves, no pods. Aphid-spread. Devastating in dry season.",treatment:["Remove infected plants immediately","Spray Actara or Dimethoate for aphids","Plant early before peak aphid season","Use SAMNUT 22 or SAMNUT 24"],pesticide:"Actara (Thiamethoxam) or Dimethoate for aphids",prevention:"Early planting. Resistant varieties. Destroy crop debris.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Contact your state ADP."},
  "cowpea mosaic":{category:"crops",disease:"Cowpea Mosaic Virus",subject:"Cowpea/Beans",severity:"moderate",description:"Yellow-green mosaic, stunted plants, reduced yields. Aphid and beetle spread.",treatment:["Remove severely infected plants","Spray Cypermethrin for aphids and beetles","Plant IT90K-277-2 or IT97K-499-35","Keep field weed-free"],pesticide:"Cypermethrin or Dimethoate spray",prevention:"Certified seeds. Insect control. Weed management.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "plantain sigatoka":{category:"crops",disease:"Black Sigatoka (Plantain)",subject:"Plantain/Banana",severity:"severe",description:"Black/dark brown leaf streaks. Leaves die early. Fruit fails to fill.",treatment:["Remove and destroy infected leaves","Spray Mancozeb or Propiconazole every 3 weeks","Improve spacing for air circulation","Bag bunches with plastic"],pesticide:"Dithane M-45 (Mancozeb) or Tilt (Propiconazole)",prevention:"Resistant varieties. Widen spacing. Remove dead leaves regularly.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "cocoa pod rot":{category:"crops",disease:"Cocoa Black Pod Disease",subject:"Cocoa",severity:"severe",description:"Black rotting patches on pods. Rapid spread in wet season. Phytophthora fungus.",treatment:["Remove and destroy infected pods immediately","Spray Copper Oxychloride on healthy pods","Prune canopy for airflow","Harvest ripe pods promptly"],pesticide:"Copper Oxychloride or Ridomil spray every 2-3 weeks",prevention:"Regular pruning. Sanitation. Remove all mummified pods.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Contact CRIN for technical support."},
  // POULTRY
  "newcastle":{category:"poultry",disease:"Newcastle Disease (NCD)",subject:"Chicken/Poultry",severity:"severe",description:"Gasping, twisted neck, green diarrhoea, sudden deaths. Can wipe out entire flock in days.",treatment:["Isolate all sick birds immediately","Vaccinate all healthy birds with Lasota NOW","Bury or burn dead birds safely","Disinfect pen with Izal or formalin"],pesticide:"Lasota ND Vaccine + broad-spectrum antibiotics",prevention:"Vaccinate Day 1, Day 14, every 3 months. Strict biosecurity.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Contact a vet immediately if losses exceed 5% in one day. Newcastle is notifiable."},
  "gumboro":{category:"poultry",disease:"Gumboro Disease (IBD)",subject:"Chicken/Poultry",severity:"severe",description:"Ruffled feathers, white watery droppings, hunched birds aged 3-6 weeks. Destroys immune system.",treatment:["Isolate affected birds","Provide electrolytes in drinking water","Vaccinate healthy chicks with IBD vaccine","Increase warmth in pen"],pesticide:"IBD Gumboro Vaccine + antibiotics for secondary infections",prevention:"Vaccinate Day 14 and Day 28. Disinfect between batches.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Consult a vet for correct vaccine schedule."},
  "coccidiosis":{category:"poultry",disease:"Coccidiosis",subject:"Chicken/Poultry",severity:"moderate",description:"Bloody dark droppings, loss of appetite, drooping wings. Eimeria parasites in wet litter.",treatment:["Add Amprolium to water 5-7 days","Remove and replace wet litter","Improve drainage around pen","Provide vitamins A and K"],pesticide:"Amprolium (Amprol) or Embazin Forte in water",prevention:"Dry litter. Avoid overcrowding. Coccidiostats in starter feed.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Consult vet for correct Amprolium dosage."},
  "fowl pox":{category:"poultry",disease:"Fowl Pox",subject:"Chicken/Poultry",severity:"moderate",description:"Wart-like scabs on comb, wattles, face. White patches inside mouth. Mosquito-spread.",treatment:["Isolate affected birds","Apply iodine to skin lesions","Vaccinate healthy birds with Fowl Pox vaccine","Eliminate mosquito breeding sites"],pesticide:"Fowl Pox Vaccine (wing-web). Tetracycline for secondary infections.",prevention:"Vaccinate at 6-8 weeks. Screen pens against mosquitoes.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "marek's disease":{category:"poultry",disease:"Marek's Disease",subject:"Chicken/Poultry",severity:"severe",description:"Leg and wing paralysis, grey eye, weight loss in 6-20 week birds. Herpesvirus. No cure.",treatment:["No cure — cull severely affected birds humanely","Vaccinate ALL day-old chicks at hatchery","Strict all-in all-out flock management","Thoroughly disinfect between flocks"],pesticide:"Marek's Disease Vaccine (day-old vaccination only)",prevention:"Vaccinate ALL chicks at day old. Never buy unvaccinated birds.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Marek's vaccine MUST be given at hatchery."},
  "avian typhoid":{category:"poultry",disease:"Fowl Typhoid (Salmonella)",subject:"Chicken/Poultry",severity:"moderate",description:"Greenish-yellow diarrhoea, pale comb, sudden deaths in adult birds.",treatment:["Treat with Enrofloxacin in water 5 days","Isolate sick birds","Disinfect drinkers and feeders daily","Prevent wild birds in pen"],pesticide:"Enrofloxacin 10% (Baytril) in water — use vet prescription",prevention:"Vaccination. Buy from reputable hatcheries.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Antibiotic use must be under vet prescription."},
  // FISH
  "columnaris":{category:"fish",disease:"Columnaris (Saddle Rot)",subject:"Catfish/Tilapia",severity:"severe",description:"White/grey patches on skin, fins, gills. Fish breathe rapidly at surface. Kills in 24-48 hours.",treatment:["30-50% water change immediately","Add 3-5g salt per litre","Terramycin in feed or water","Reduce stocking density urgently"],pesticide:"Terramycin (Oxytetracycline) or Potassium Permanganate bath 10mg/L",prevention:"Good water quality. No overcrowding. Quarantine new fish.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Act immediately — Columnaris kills in 24-48 hours."},
  "gill disease":{category:"fish",disease:"Bacterial Gill Disease",subject:"Catfish/Tilapia",severity:"moderate",description:"Fish gasping at surface, pale or dark gills, reduced appetite. High ammonia in water.",treatment:["Change 40% of pond water immediately","Increase aeration","Potassium Permanganate bath 10mg/L for 20 minutes","Remove uneaten feed and dead fish"],pesticide:"Potassium Permanganate + Salt bath",prevention:"Test water weekly. Avoid overfeeding. Regular partial water changes.",confidence:"high",disclaimer:"AgroDoc AI is advisory only."},
  "ich":{category:"fish",disease:"White Spot Disease (Ich)",subject:"Fish",severity:"moderate",description:"White salt-grain spots on body. Fish scratch against pond walls, erratic swimming.",treatment:["Raise water temperature to 28-30°C if possible","Add 3g salt per litre for 7-10 days","Formalin 25ml per 1,000 litres for 1 hour","30% water change after treatment"],pesticide:"Formalin solution or Malachite Green (use carefully — toxic at high doses)",prevention:"Quarantine new fish 2 weeks. Keep water temperature above 25°C.",confidence:"high",disclaimer:"AgroDoc AI is advisory only. Handle Formalin carefully — toxic chemical."},
  "catfish aeromoniasis":{category:"fish",disease:"Aeromonas Infection (Ulcer Disease)",subject:"Catfish",severity:"severe",description:"Red ulcers on skin, haemorrhage at fin base, bloated belly, rapid deaths.",treatment:["Immediate 50% water change","Oxytetracycline in feed 10 days","Salt bath 5g/litre for 30 minutes","Remove dead fish immediately"],pesticide:"Terramycin (Oxytetracycline) in medicated feed",prevention:"Clean water. Avoid fish injuries. Reduce stocking density.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Aeromonas spreads fast — contact state Fisheries Department."},
  "tilapia lake virus":{category:"fish",disease:"Tilapia Lake Virus (TiLV)",subject:"Tilapia",severity:"severe",description:"Sunken eyes, skin ulcers, abnormal swimming, mass mortality. Notifiable viral disease.",treatment:["No cure — immediate containment required","Remove and safely dispose of all dead fish","Disinfect all equipment with chlorine","Report to state fisheries department immediately"],pesticide:"No treatment — biosecurity and containment only",prevention:"Certified stock from reputable hatcheries only.",confidence:"medium",disclaimer:"⚠️ AgroDoc AI is advisory only. TiLV is notifiable — report to state Fisheries Department immediately."},
  // LIVESTOCK
  "ppr":{category:"livestock",disease:"PPR (Peste des Petits Ruminants)",subject:"Goat/Sheep",severity:"severe",description:"High fever, eye/nose discharge, mouth sores, severe diarrhoea, pneumonia. Kills 80-90% of flock.",treatment:["Isolate ALL sick animals immediately","Vaccinate all healthy animals NOW","Oxytetracycline for secondary pneumonia","Report to state vet — PPR is notifiable"],pesticide:"PPR Vaccine + Oxytetracycline LA for secondary infections",prevention:"Vaccinate every 3 years. Never mix unknown animals.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. PPR IS NOTIFIABLE — contact state vet and NAFDAC immediately. Do not move animals."},
  "foot and mouth":{category:"livestock",disease:"Foot and Mouth Disease (FMD)",subject:"Cattle/Goat",severity:"severe",description:"Fever, blisters on mouth and feet, heavy salivation, severe limping. Highly contagious.",treatment:["Isolate ALL affected animals immediately","Wash mouth lesions with sodium bicarbonate","Treat foot lesions with antiseptic spray","Notify state vet immediately"],pesticide:"FMD Vaccine for prevention. Supportive care — no cure.",prevention:"Vaccinate twice yearly. Disinfect equipment. Control animal movement.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. FMD IS NOTIFIABLE — contact state vet and NAFDAC. Movement of animals is illegal during outbreak."},
  "african swine fever":{category:"livestock",disease:"African Swine Fever (ASF)",subject:"Pig",severity:"severe",description:"High fever, red/blue skin discoloration, bloody diarrhoea, sudden deaths. 100% fatal. Highly contagious.",treatment:["No treatment — infected pigs must be culled immediately","Report to state vet immediately","Disinfect all buildings with caustic soda","Do not sell or move any pigs under any circumstances"],pesticide:"No treatment — biosecurity and culling only",prevention:"Strict biosecurity. No wild boar contact. Never feed kitchen waste to pigs.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. ASF IS FATAL AND NOTIFIABLE. Report to state vet immediately — illegal to move infected pigs."},
  "trypanosomiasis":{category:"livestock",disease:"Trypanosomiasis (Sleeping Sickness)",subject:"Cattle/Goat",severity:"severe",description:"Anaemia, weight loss, rough coat, weakness, death if untreated. Tsetse fly transmission.",treatment:["Treat with Berenil injection","Repeat after 3 weeks","Control tsetse fly with insecticide traps","Move animals away from tsetse-infested bush"],pesticide:"Berenil (Diminazene aceturate) — vet-administered injection only",prevention:"Trypanotolerant breeds. Tsetse control. Avoid high-risk bush grazing.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. Berenil MUST be given by a certified vet — overdose is fatal to animals."},
  "lumpy skin":{category:"livestock",disease:"Lumpy Skin Disease (LSD)",subject:"Cattle",severity:"moderate",description:"Nodules/lumps on skin, fever, reduced milk, nasal discharge. Spread by biting insects.",treatment:["Isolate affected cattle","Treat skin lesions with antiseptic","Antibiotics for secondary infections","Vaccinate remaining herd immediately"],pesticide:"LSD Vaccine. Oxytetracycline LA for secondary infections.",prevention:"Vaccinate annually. Control biting insects. Avoid movement during outbreaks.",confidence:"high",disclaimer:"⚠️ AgroDoc AI is advisory only. LSD is notifiable in Nigeria — report to state vet."},
};

function tryOfflineCache(text){
  if(!text)return null;
  const lower=text.toLowerCase();
  const key=Object.keys(OFFLINE_CACHE).find(k=>{const p=k.split(" ");return lower.includes(p[0])&&(p.length<2||lower.includes(p[1]));});
  if(key)return OFFLINE_CACHE[key];
  const fallback=Object.keys(OFFLINE_CACHE).find(k=>lower.includes(k.split(" ")[0]));
  return fallback?OFFLINE_CACHE[fallback]:null;
}

function buildSystemPrompt(lang="en",mode="farmer",category="crops"){
  return `You are AgroDoc AI, Nigeria's expert AI farm doctor. ${LANG_PROMPTS[lang]||LANG_PROMPTS.en}
${CAT_INSTRUCTIONS[category]||CAT_INSTRUCTIONS.crops}
${mode==="dealer"?"Detailed technical info — scientific names, dosage rates, management protocols.":"Simple practical language — locally available Nigerian brand names."}
${lang==="pcm"?"For Pidgin: be warm and friendly like a knowledgeable Nigerian neighbour.":""}

MANDATORY SAFETY RULES — NEVER SKIP:
1. disclaimer field MUST always say: "AgroDoc AI is advisory only. Not a substitute for a certified agronomist or veterinarian."
2. For severe or notifiable diseases (Newcastle, FMD, PPR, ASF, CBPP, TiLV, Marek's), ALWAYS tell farmer to contact their state vet or ADP immediately.
3. For chemicals/drugs, always mention correct dosage and professional consultation.

Return ONLY raw JSON (no markdown, no backticks):
{"category":"${category}","subject":"crop or animal name in English","disease":"condition name","severity":"mild|moderate|severe","description":"clear explanation","treatment":["step1","step2","step3","step4"],"pesticide":"Nigerian product name and active ingredient (N/A if not applicable)","prevention":"practical prevention advice","confidence":"high|medium|low","disclaimer":"mandatory advisory disclaimer + vet/ADP referral if severe","whatsappSummary":"2-sentence farmer-friendly summary for sharing with neighbours"}
If healthy: set disease to 'Healthy Crop/Animal' and give care tips. All text in selected language EXCEPT subject (always English).`;
}

async function diagnose({imageBase64,imageType="image/jpeg",text,lang="en",mode="farmer",category="crops"}){
  const content=[];
  if(imageBase64)content.push({type:"image",source:{type:"base64",media_type:imageType,data:imageBase64}});
  content.push({type:"text",text:text?.trim()||`Analyse this ${category} for any disease or health problem.`});
  const res=await axios.post("https://api.anthropic.com/v1/messages",{model:"claude-sonnet-4-20250514",max_tokens:1200,system:buildSystemPrompt(lang,mode,category),messages:[{role:"user",content}]},{headers:{"x-api-key":process.env.ANTHROPIC_API_KEY,"anthropic-version":"2023-06-01","content-type":"application/json"},timeout:30000});
  const raw=res.data.content?.map(b=>b.text||"").join("").trim();
  return JSON.parse(raw.replace(/```json|```/g,"").trim());
}

module.exports={diagnose,tryOfflineCache,OFFLINE_CACHE,CACHE_VERSION};
